name: Tests
on:
  pull_request:
    branches:
      - main
      - beta
    paths:
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'powershell'

jobs:
  e2e:
    strategy:
      matrix:
        os: [ self-windows ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test:e2e
