name: Tests
on:
  push:
    branches:
      - main
      - beta
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'
  pull_request:
    branches:
      - main
      - beta
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    strategy:
      matrix:
        os: [ windowsvm, ubuntuvm ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Runner workspace path (linux)
        if: runner.os == 'Linux'
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
      - name: Runner workspace path (linux)
        if: runner.os == 'Windows'
        run: |
          echo "Cleaning up previous run"
          rd /s /q "${{ github.workspace }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test:e2e
